[[main]]
  name = "Home"
  url = "#about"
  weight = 10

[[main]]
  name = "Skills"
  url = "#skills"
  weight = 20

[[main]]
  name = "Experience"
  url = "#experience"
  weight = 30

[[main]]
  name = "Courses"
  url = "#self_study_courses"
  weight = 40
  
  [[main]]
  name = "Projects"
  url = "#projects"
  weight = 50

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 60
